### ISSUE TITLE
State not working

### ISSUE THREAD

**Issue by jn6415** [koalyptus/TableFilter#301] opened 2016-09-25 22:19 UTC
I'm trying to work on a code to preserve the table state (e.g., page #) so if someone clicks the back button it would return to the correct page (e.g., Page 2 out of 10). I have this code:
var leads_Props = {  
        col_7: 'checklist',
        col_8: 'checklist',
        paging: true, state: { types: ['hash'], page_length: true };
        paging_length: 25,
        results_per_page: ['# rows per page',[25,50]],  
        rows_counter: true,  
        rows_counter_text: "Rows:",  
        btn_reset: true,  
        btn_next_page_html: '<a href="javascript:;" style="margin:3px;">Next ></a>',  
        btn_prev_page_html: '<a href="javascript:;" style="margin:3px;">< Previous</a>',  
        btn_last_page_html: '<a href="javascript:;" style="margin:3px;"> Last >|</a>',  
        btn_first_page_html: '<a href="javascript:;" style="margin:3px;"><| First</a>',  
        loader: true,  
        loader_html: '<h4 style="color:maroon;">Loading, please wait...</h4>'
      
    };  

However, with the "state : { };" in the code the table itself will not load. If I remove the "state : {};" the table loads correctly but cannot preserve the page # state.

Any ideas?

**Comment by koalyptus** [comment] 2016-09-25 23:12
Hi @jn6415,
From what I see in your configuration code, it should read:
```
...
state: { types: ['hash'], page_length: true },
...
```
and not 
```
...
state: { types: ['hash'], page_length: true };
...
```

**Comment by jn6415** [comment] 2016-09-27 17:26
Thanks. The comma got the table to load. Now that I have the state set, if I click on an object within my table (edit object) which takes me to a second page, when I return to the table page the filters and/or page # are not remembered. Any ideas on how I can make the filters and page number persistent if I move to an edit page and go back?

**Comment by koalyptus** [comment] 2016-09-27 21:31
All the state options are featured in the demo mentioned above, from what I can see you are persisting only the page length.

**Comment by koalyptus** [comment] 2016-09-27 21:34
Check this demo too: 
http://koalyptus.github.io/TableFilter/persistence.html

**Comment by jn6415** [comment] 2016-09-28 01:00
Thanks! Here is my updated code, the state still doesn't persist.
....
        state: {
          types: ['hash'],
          filters: true,
          page_number: true,
          page_length: true,
          sort: true
        },
        paging: true,
.....

**Comment by koalyptus** [comment] 2016-09-28 02:03
Exhausting options... :
- ensure you have a recent version greater to v0.2.56, this was the last change occurred on this feature: #282

**Comment by koalyptus** [comment] 2016-10-09 03:47
Closing as not able to reproduce the issue.
Any further ticket related to this, please provide relevant steps to reproduce the issue.

**Closed by koalyptus** 2016-10-09 03:47 UTC
