### ISSUE TITLE
Error reading page_length from local_storage

### ISSUE THREAD

**Issue by IObregon** [koalyptus/TableFilter#424] opened 2017-03-24 12:47 UTC
I have a table with popup_filtering active and state saved to local_storage. If I do a filtering that returns 0 result and after that i reload the page the next error appears in javascript console:

> Uncaught TypeError: Cannot set property 'selected' of undefined

I followed this error till this function (on line 2150 is where the error happens) :

```
e.prototype.onChangeResultsPerPage = function() {
                var t = this.tf;
                if (this.isEnabled()) {
                    this.emitter.emit("before-page-length-change", t);
                    var e = this.resultsPerPageSlc,
                        i = e.selectedIndex,
                        s = this.pageSelectorType === f.SELECT ? this.pagingSlc.selectedIndex : parseInt(this.pagingSlc.value - 1, 10);
                    if (this.pagingLength = parseInt(e.options[i].value, 10), this.startPagingRow = this.pagingLength * s, !isNaN(this.pagingLength) && (this.startPagingRow >= t.nbFilterableRows && (this.startPagingRow = t.nbFilterableRows - this.pagingLength), this.setPagingInfo(), this.pageSelectorType === f.SELECT)) {
                        var n = this.pagingSlc.options.length - 1 <= s ? this.pagingSlc.options.length - 1 : s;
                        **this.pagingSlc.options[n].selected = !0**
                    }
                    this.emitter.emit("after-page-length-change", t, this.pagingLength)
                }
            }
```
I have this problem in a more complex context, if you are not able to reproduce it, I can try to give you a demo or something like that.

Thank you for your great library and sharing it with all of us.

**Comment by koalyptus** [comment] 2017-03-25 00:45
Thanks for pointing this out @IObregon, I can easily reproduce the issue on this demo:
http://koalyptus.github.io/TableFilter/persistence.html
It seems to be related to page length selection persistence, I will investigate and fix it in the coming days.
Cheers

**Comment by koalyptus** [comment] 2017-03-25 04:52
Starting from `v0.5.4` the above bug should be fixed.
Tell me how it goes.

**Closed** 2017-03-30 11:26 UTC
Labels: bug

**Comment by IObregon** [comment] 2017-03-31 09:45
Thank you for the fast answer. 
I have to try with the last version.
Are you going to do a new release or should I get the code from master?

Again thanks for your answer and great proyect.

**Comment by koalyptus** [comment] 2017-03-31 11:32
No worries, you can pull master or take the latest version from npm.
Cheers

**Comment by IObregon** [comment] 2017-04-11 10:30
Now It works perfectly.
