### ISSUE TITLE
Click on Links not working

### ISSUE THREAD

**Issue by sacostat** [koalyptus/TableFilter#691] opened 2019-03-15 14:44 UTC
After adding the tablefiltered.js file into my project, all links (<a>) stopped working. Clicking on the link will not open anything, even though it has the right settings. Only way to open links is using secondary click > open in new tab. Have removed the tablefiltered.js file and verify the issue is with the file itself.

**Reproduction steps:**

1. Add a link into the project, for example: <a href="">Link</a>
2. Click on the link, no result
3. Secondary click, open in new tab, works

**Expected behavior:**

Users should be able to click and open links as normal.

**Observed behavior:**

Clicking is not opening any links.

**Screenshots and GIFs**

**TableFilter version:** Downloaded two weeks ago
**Browser and version:** Chrome 72.0.3626.121, FF 65.0.1
**OS and version:** Mac High Sierra

**Additional information:**

* Problem started happening recently, didn't happen in an older version of 
TableFilter: No
* Problem can be reliably reproduced, doesn't happen randomly: Yes

**Comment by cjohnsonuk** [comment] 2019-03-15 19:59
I had something similar last week. I initiated table filter then ran a script called autolink to find URLs and make then clickable. Table filter worked before with links of created but not with the automatic ones. I just switched the order do it created the links and then initiated table filter. Not sure if this helps

**Comment by sacostat** [comment] 2019-03-18 16:05
@cjohnsonuk Thanks for that tip! If you had that autolink script to share, it would be great. But I do want to understand why would links stop working while using this in the first place. I would imagine that links should always work as the tablefiltered.js should only affect the functionality of the table itself.

**Comment by koalyptus** [comment] 2019-03-19 02:47
@sacostat assuming you are using `tablefilter.js`, as you mention `tablefiltered.js`
I can't repro the issue for the moment, this example for instance contains links in the table and in the page (navigation bar etc): http://www.tablefilter.com/filters-visibility.html, links seem to work correctly.
TableFilter does nothing in particular with links on the page. Only scenarios I can think of at this stage, are:
- a script adding a on click event handler on body element that prevents the default behaviour of a click or that goes wrong 
- a script adding a CSS style that prevents clicks, something like `pointer-events: none`
Importing TableFilter would interfere somehow with that script and cause an exception... just a theory.

Would be nice to have a example reproducing the issue to have more visibility.
Please check if you have javascript errors in your console and provide the TableFilter's version.

Cheers

**Comment by cjohnsonuk** [comment] 2019-03-22 15:47
This is the source of the autolink script:
https://github.com/gregjacobs/Autolinker.js
Its taken a while to find it as there are many and I had to wait until I had access to the box I used it on.

**Comment by koalyptus** [comment] 2019-04-15 12:30
closing as I can't reproduce the issue at this stage.

**Closed by koalyptus** 2019-04-15 12:30 UTC
