### ISSUE TITLE
getFilteredData affected by pagination.

### ISSUE THREAD

**Issue by cjohnsonuk** [koalyptus/TableFilter#250] opened 2016-06-29 22:59 UTC
Feature request...?
**Background**
I've just noticed an effect I wasn't expecting.  I've used getFilteredData in a to create some stats on the visible data in my table.  This works well for my test data.  However the list was still very long on the live data.  I found a previous issue logged here relating to fixing the table header row to the top of the screen when scrolling down the page but that didn't appear to have a working solution so I used the toggle pagination code so that its not as far to scroll to confirm the column headers.  
**Issue**
I noticed that my stats created from the data returned by getFilteredData appear to be calculated based on the _visible rows_, not just the filtered rows.  getFilteredData appears to return the rows from the table that are 'visible', rather than what I expected which was the rows that match the filters.  Rows not visible due to pagination appear to be omitted from the data returned.  I'll confirm this tomorrow.  I think I can get round this by turning off pagination doing my calculations and then turning it back on again.  
**Request**
It would be nice to have either a parameter in getFilteredData to ignore the effects of pagination or to have another function called getVisibleData that does what getFilteredData does and for getFilteredData to return the data matching the active filters whether its hidden by pagination or not..

**Comment by koalyptus** [comment] 2016-06-30 23:11
Thanks for your detailed ticket. You shouldn't have to turn off pagination to get the filtered data but from memory your description seems correct. Anyway I like your idea of having an explicit getVisibleData method to make it clear what you get.
Cheers

**Comment by cjohnsonuk** [comment] 2016-07-01 09:02
I can get the filtered data without turning off pagination but it only returns the 10 rows on the screen so the stats I'm showing only refer to the visible rows.  I want the stats to be calculated from the rows matching the filter (s), not just the rows showing due to pagination. Turning off pagination allows me to get the full filtered data set to do the stats calculation but... and I've only just realised this, my stats calculation is triggered using   "on_after_filter" which is triggered when I toggle pagination back on again (so my stats are then recalculated again).

**Comment by koalyptus** [comment] 2016-07-02 09:11
I cannot reproduce the issue `getFilteredData()` behaves as expected when `paging` is on. If you open the following demo http://koalyptus.github.io/TableFilter/paging.html and then set `>100000` in the `POP` filter and hit enter you will get `70` results.
The `tf.getFilteredData().length` instruction in the browser's console returns the same number whatever page you select, it definitely does not return the number of 'visible` rows. Consequently your issue has to do with the `on_after_filter` callback as it is fired before the pagination process starts.

My advice is to keep paging on and try for calculating your stats to hook into the `grouped-by-page` event instead:
```
tf.emitter.on(['grouped-by-page'], function(tf, paging){
  console.log(tf.getFilteredData().length);
});
```  
This should give you the expected number rows.

**Comment by cjohnsonuk** [comment] 2016-07-03 22:33
Not sure I've understood you or made my issue clear.  I don't think it's the .length that was the issue. My script calculates the counts of each data category (not the number of rows) in my main table but when my main table has pagination on the totals appear to be on a per page basis.  I want to be able to return the whole table filtered data as an array not just the visible (paged) filtered data on the current page.  So if I filter my 800 rows to show 400 as 4 pages of 100 rows and run getfiltereddata against this table the data I get back is just off the visible 100 rows. Changing the sort order in the paged table changes the category counts because different data is visible.  For example I might select all boys in my main table.  The get filtered data function pulls the filtered data  from the main table and after wotking out the columns that have selects as the filter type counts the number of matching entries for each of the categories from the select.  Eg number of boys of each age, numbers of boys from each town, number of boys with each grade, number of behaviour incidents. It then calculates the % of each grade/ town/ age / issue as a proportion of the visible data ( eg just the boys) and of the whole table (ie boys and girls).  Data is displayed in a table to allow the end user to quickly change the filters in the main table to see what factors have the biggest effects on the grades etc.  This has worked fine until I added paging to the main table at which point the category counts now only count totals from what you can see on the current page.  The data returned by get filtered data appears to be affected by paging and it only returns that data from the current page. The live system for this contains confidential data and so is password protected but if I'm still not clear I'll stick an example on my own hosting with some demo data, a picture says a thousand words etc

**Comment by koalyptus** [comment] 2016-07-04 03:01
Yeah same for me, not sure you understood my comment :smile: 
In short, what I am saying in previous comment is that I cannot reproduce the issue you are describing. When paging is on `getFilteredData()` returns the whole filtered dataset and **not** only the visible data of current page and to support that I described how to verify the expected behaviour in the demo page. The `length` property is just a helper to check the dataset length is as expected (whole filtered dataset).
So `paging` alone is not enough to explain why you get only the `visible` data... Something else must interfere. Does it make sense?

**Comment by cjohnsonuk** [comment] 2016-07-04 17:51
OK. I'll give it another test as soon as I get a chance

**Comment by koalyptus** [comment] 2016-07-23 07:50
Closing this issue, you can always re-open if necessary.

**Closed by koalyptus** 2016-07-23 07:50 UTC

**Comment by cjohnsonuk** [comment] 2016-11-02 10:36
Looking back at this again...
We're reviewing another piece of code that uses colOps to display a sum in a named div as per the demo.

On your demo page : http://koalyptus.github.io/TableFilter/column-calculations.html

run this in the console : (it's basically the same as is on the page already but with pagination turned on)

```
tf.destroy();
var tf = new TableFilter(
        document.querySelector('#calc-demo'),
        {
            base_path: 'tablefilter/',
            alternate_rows: true,
            rows_counter: true,
            rows_counter_text: 'Items: ',
            btn_reset: true,
          paging: true,
          results_per_page: ['Results per page',[5,10,25,50,100]],  
          status_bar: true,
            col_types: [
                'none', 'string', 'number',
                'number', 'number', 'number',
                'number', 'number', 'number',
                'number', 'number', 'number',
                'number', 'number', 'number',
                'number'
            ],
            sort_select: true,
            col_1: 'select',

            // extensions: sort and column operations
            extensions: [
                {
                    name: 'sort'
                }, {
                    name: 'colOps',
                    id: [
                        'demosum2', 'demomean2', 'demomin2', 'demoLQ2', 'demoMed2', 'demoUQ2', 'demomax2',
                        'demosum3', 'demomean3', 'demomin3', 'demoLQ3', 'demoMed3', 'demoUQ3', 'demomax3',
                        'demosum4', 'demomean4', 'demomin4', 'demoLQ4', 'demoMed4', 'demoUQ4', 'demomax4',
                        'demosum5', 'demomean5', 'demomin5', 'demoLQ5', 'demoMed5', 'demoUQ5', 'demomax5',
                        'demosum6', 'demomean6', 'demomin6', 'demoLQ6', 'demoMed6', 'demoUQ6', 'demomax6',
                        'demosum7', 'demomean7', 'demomin7', 'demoLQ7', 'demoMed7', 'demoUQ7', 'demomax7',
                        'demosum8', 'demomean8', 'demomin8', 'demoLQ8', 'demoMed8', 'demoUQ8', 'demomax8',
                        'demosum9', 'demomean9', 'demomin9', 'demoLQ9', 'demoMed9', 'demoUQ9', 'demomax9',
                        'demosum10', 'demomean10', 'demomin10', 'demoLQ10', 'demoMed10', 'demoUQ10', 'demomax10',
                        'demosum11', 'demomean11', 'demomin11', 'demoLQ11', 'demoMed11', 'demoUQ11', 'demomax11',
                        'demosum12', 'demomean12', 'demomin12', 'demoLQ12', 'demoMed12', 'demoUQ12', 'demomax12',
                        'demosum13', 'demomean13', 'demomin13', 'demoLQ13', 'demoMed13', 'demoUQ13', 'demomax13',
                        'demosum14', 'demomean14', 'demomin14', 'demoLQ14', 'demoMed14', 'demoUQ14', 'demomax14',
                        'demosum15', 'demomean15', 'demomin15', 'demoLQ15', 'demoMed15', 'demoUQ15', 'demomax15'
                    ],
                    col: [
                        2, 2, 2, 2, 2, 2, 2,
                        3, 3, 3, 3, 3, 3, 3,
                        4, 4, 4, 4, 4, 4, 4,
                        5, 5, 5, 5, 5, 5, 5,
                        6, 6, 6, 6, 6, 6, 6,
                        7, 7, 7, 7, 7, 7, 7,
                        8, 8, 8, 8, 8, 8, 8,
                        9, 9, 9, 9, 9, 9, 9,
                        10, 10, 10, 10, 10, 10, 10,
                        11, 11, 11, 11, 11, 11, 11,
                        12, 12, 12, 12, 12, 12, 12,
                        13, 13, 13, 13, 13, 13, 13,
                        14, 14, 14, 14, 14, 14, 14,
                        15, 15, 15, 15, 15, 15, 15
                    ],
                    operation: [
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max',
                        'sum', 'mean', 'min', 'Q1', 'median', 'Q3', 'max'
                    ],
                    decimal_precision: [
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1,
                        1, 1, 1, 1, 1, 1, 1
                    ]
                }
            ]
        }
    );
    tf.init();
```

and you will see that the colOps operations don't like data that's paginated only calculating the sum of the visible rows on the first page.  
EG in column A filter box type <40 and it shows 5 rows out of a total of 15 but the col ops is working on visible / displayed data rather than all the filtered rows which (certainly in my case) would be a lot more useful.  Assuming that its currently functioning correctly and showing "Displayed rows" then you would expect changing the page number to view the 2nd and 3rd pages would also recalculate the sum of displayed rows but it doesn't.  It still shows the sum of the 5 values on page 1.  
I'm only using pagination to minimise the amount of scrolling to see the stats in the colOps table.
 
We'd been using ColOps to calculate a sum, but as the data set got bigger and the table paginated the ColOps sum stopped using the whole table....
